name: base_project
description: base project

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_svg: ^0.19.3
  shared_preferences: ^2.0.7
  provider: ^6.0.2
  google_fonts: ^2.2.0
  animate_do: ^2.1.0
  url_launcher: ^6.0.10
  auto_size_text: ^3.0.0
  shimmer: ^2.0.0
  responsive_framework: ^0.1.5
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/